import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import {Mulish} from "next/font/google";
import Footer from "@/app/components/Footer";

const mulish=()=>({
  weight: ['300','400','500','600','700','800','900'],
  subsets: ['latin'],
  display: 'swap',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "THE ROSSSH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
